# Generated by Django 4.2.7 on 2026-09-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='mirror_audi_created_2f9d99_idx',
            old_name='mirror_audi_created_d4f0cf_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='mirror_audi_event_t_3c1d78_idx',
            old_name='mirror_audi_event_t_7c0c66_idx',
        ),
        migrations.RenameIndex(
            model_name='intentcontract',
            new_name='mirror_inte_user_id_b5243d_idx',
            old_name='mirror_inten_user_id_9e3fe9_idx',
        ),
        migrations.RenameIndex(
            model_name='intentcontract',
            new_name='mirror_inte_expires_fc1c8f_idx',
            old_name='mirror_inten_expires_5d69dc_idx',
        ),
        migrations.RenameIndex(
            model_name='toolcall',
            new_name='mirror_tool_created_ca0599_idx',
            old_name='mirror_tool_created_7d6b89_idx',
        ),
        migrations.RenameIndex(
            model_name='toolcall',
            new_name='mirror_tool_decisio_17c487_idx',
            old_name='mirror_tool_decisio_445af8_idx',
        ),
        migrations.RenameIndex(
            model_name='toolcall',
            new_name='mirror_tool_agent_i_119502_idx',
            old_name='mirror_tool_agent_i_f189f5_idx',
        ),
    ]
